### ISSUE TITLE
question about reconstruction precision

### ISSUE THREAD

**Issue by CanCanZeng** [qianyizh/ElasticReconstruction#10]
Hi @qianyizh , I am looking for an algorithm that is offline and can produce **very fined details** from RGB-D data. I find this project, but the provided results on _http://redwood-data.org/indoor/models.html_ website seem not so precise. Is `ElasticReconstrction` the same as `Robust Reconstruction of Indoor Scene`, or there are some revisions for detail reconstruction?

I'm confused that SfM+MVS can produce very fined detail from only RGB data, but most algorithm that I find can only produce rather coarse result from RGB-D data, why rare research is focused on reconstruct precise result from RGB-D data, I don't understand.

Do you know any algorithm that suits me, thank you.

**Comment by qianyizh** [comment]
``Robust reconstruction of indoor scenes`` supersedes ``ElasticReconstruction``. You can find its latest implementation in our open source project [Open3D](http://www.open3d.org/), or https://github.com/IntelVCL/Open3D/  The reconstruction system tutorial is at http://www.open3d.org/docs/tutorial/ReconstructionSystem/index.html

And yes, we are aware of SfM+MVS methods. In fact, we have set up a benchmark called TanksAndTemples to evaluate the latest SfM+MVS pipelines. https://www.tanksandtemples.org/

It is hard to explain the difference between these two types of methods in a short post. But in a nutshell, RGB-D based methods tend to be more robust for the simple reason that it has a depth channel. When you are scanning indoor environment, it is very common to scan featureless objects such as a white wall or desk. SfM+MVS cannot extract any information from it. But a depth channel can provide such information. IMO, SfM+MVS is more suited to scan feature-rich objects and large outdoor scenes. RGB-D based methods are more suited to scan indoor environment and small scale scenes.

**Comment by CanCanZeng** [comment]
Thank you for your help! I will try Open3D.
