### ISSUE TITLE
Is there a Linux version?

### ISSUE THREAD

**Issue by shuluoshu** [qianyizh/ElasticReconstruction#9]
Hi, @qianyizh , I wonder if there is a Linux version? Since I am not familiar with the deploy on Windows ? Thanks so much!

**Comment by qianyizh** [comment]
We are working on a major release of a 3D reconstruction library and it will be coming very soon.
The new library will have all functionalities of this old repository (and is much better in terms of performance and accuracy).

I will update it here.

**Comment by mayankamedhe** [comment]
@qianyizh Is the linux version available now?

**Comment by qianyizh** [comment]
Check this out:
https://github.com/IntelVCL/Open3D

It includes a complete reconstruction system:
http://www.open3d.org/docs/tutorial/ReconstructionSystem/index.html

The nonrigid part is still missing, but will be added to Open3D very soon.

**Comment by mayankamedhe** [comment]
Thanks a lot @qianyizh!
